src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=24)
     */
    private $display_name;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="sender")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="user")
     */
    private $notifications;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Follower", mappedBy="user")
     */
    private $followers;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Follower", mappedBy="follower")
     */
    private $following;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ChatConversation", mappedBy="participants")
     */
    private $chatConversations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="user")
     */
    private $favorites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Upload", mappedBy="uploader")
     */
    private $uploads;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $theme_color;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->followers = new ArrayCollection();
        $this->chatConversations = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->uploads = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setSender($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getSender() === $this) {
                $post->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setUser($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getUser() === $this) {
                $notification->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Follower[]
     */
    public function getFollowers(): Collection
    {
        return $this->followers;
    }

    public function addFollower(Follower $follower): self
    {
        if (!$this->followers->contains($follower)) {
            $this->followers[] = $follower;
            $follower->setUser($this);
        }

        return $this;
    }

    public function removeFollower(Follower $follower): self
    {
        if ($this->followers->contains($follower)) {
            $this->followers->removeElement($follower);
            // set the owning side to null (unless already changed)
            if ($follower->getUser() === $this) {
                $follower->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Follower[]
     */
    public function getFollowing(): Collection
    {
        return $this->following;
    }

    /**
     * @return Collection|ChatConversation[]
     */
    public function getChatConversations(): Collection
    {
        return $this->chatConversations;
    }

    public function addChatConversation(ChatConversation $chatConversation): self
    {
        if (!$this->chatConversations->contains($chatConversation)) {
            $this->chatConversations[] = $chatConversation;
            $chatConversation->addParticipant($this);
        }

        return $this;
    }

    public function removeChatConversation(ChatConversation $chatConversation): self
    {
        if ($this->chatConversations->contains($chatConversation)) {
            $this->chatConversations->removeElement($chatConversation);
            $chatConversation->removeParticipant($this);
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setUser($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getUser() === $this) {
                $favorite->setUser(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return 'vive le projet tweet_academy';
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Upload[]
     */
    public function getUploads(): Collection
    {
        return $this->uploads;
    }

    public function addUpload(Upload $upload): self
    {
        if (!$this->uploads->contains($upload)) {
            $this->uploads[] = $upload;
            $upload->setUploader($this);
        }

        return $this;
    }

    public function removeUpload(Upload $upload): self
    {
        if ($this->uploads->contains($upload)) {
            $this->uploads->removeElement($upload);
            // set the owning side to null (unless already changed)
            if ($upload->getUploader() === $this) {
                $upload->setUploader(null);
            }
        }

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(?int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

templates/profile/_layout.html.twig
{% extends 'base.html.twig' %}

{% if user.avatarPath is empty %}
    {% set userAvatarPath = asset('assets/img/user-placeholder.png') %}
{% else %}
    {% set userAvatarPath = asset('upload/avatar/'~ user.avatarPath) %}
{% endif %}

{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/profile.css') }}">
{% endblock %}

{% block title %}Profile{% endblock %}

{% block seo_opengraph %}
    <meta name="image" content="{{ absolute_url(userAvatarPath) }}">
    <meta property="og:site_name" content="Ducker">
    <meta property="og:title" content="{{ user.displayName }} (@{{ user.username }})">
    <meta property="og:type" content="profile">
    <meta property="og:profile:username" content="{{ user.username }}">
    <meta property="og:image" content="{{ absolute_url(userAvatarPath) }}">
{% endblock %}

{% block user_stylesheet %}
    {% if user.themeColor is not empty %}
        <style>
            {% include 'user_theme.css.twig' with { primaryColor: user.themeColor } %}
        </style>
    {% endif %}
{% endblock %}

{% block body %}

    {% if user is not empty and user.coverPath is not empty %}
        {% set cover_url = asset('upload/banner/' ~ user.coverPath) %}
    {% else %}
        {% set cover_url = asset('assets/img/cover-placeholder.jpg') %}
    {% endif %}
    <div id="banner" class="col-12" style="background-image: url('{{ cover_url }}');">
    </div>

    <div class="nav-profile">
        <div class="container overall">
            <div class="row">
                <div class="col-lg-3">
                    <div class="profile-avatar">
                        <img src="{{ userAvatarPath }}" height="200" width="200" alt="Profile picture" class="avatar">
                    </div>
                </div>
                <div class="col-lg-6 profile-bar navbar">

                    <div id="profile-nav" class="nav navbar-expand-md">
                        <a class="nav-link" href="{{ path('profile_view', {username: user.username}) }}">
                            <div>
                                <span>Quacks</span>
                                <div><strong>{{ (user.posts|length)|number_format }}</strong></div>
                            </div>
                        </a>
                        <a class="nav-link" href="{{ path('profile_following', {username: user.username}) }}">
                            <div>
                                <span>Following</span>
                                <div><strong>{{ (user.following|length)|number_format }}</strong></div>
                            </div>
                        </a>
                        <a class="nav-link" href="{{ path('profile_followers', {username: user.username}) }}">
                            <div>
                                <span>Followers</span>
                                <div><strong>{{ (user.followers|length)|number_format }}</strong></div>
                            </div>
                        </a>
                        <a class="nav-link" href="{{ path('profile_favorites', {username: user.username}) }}">
                            <div>
                                <span>Likes</span>
                                <div><strong>{{ (user.favorites|length)|number_format }}</strong></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 profile-nav-btn-group button-profile">
                    {% if app.user is not empty %}
                        {% if app.user.id == user.id %}
                            <a href="{{ path('edit_profile', {username: user.username}) }}" class="btn btn-primary profile-nav-btn">Edit Profile</a>
                        {% else %}
                            {% set already_following = 0 %}
                            {% for f in app.user.following %}
                                {% if f.user.id == user.id %}
                                    {% set already_following = 1 %}
                                {% endif %}
                            {% endfor %}

                            {% if already_following == 0 %}
                                <button class="btn btn-primary profile-nav-btn follow">Follow</button>
                            {% else %}
                                <button class="btn btn-primary profile-nav-btn unfollow">Unfollow</button>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                {% block profile_left %}
                    <div class="profile-info">
                        <div><strong>{{ user.displayName }}</strong></div>
                        <div><small>@{{ user.username }}</small></div>
                        {% if user.city is not empty %}
                            <div><small><i class="fas fa-map-marker-alt"></i> {{ user.city }}</small></div>
                        {% endif %}
                        {% if user.gender is not empty %}
                            {% if user.gender  == "0" %}
                                <div><small><i class="fas fa-mars"></i> Male</small></div>
                            {% elseif  user.gender  == "1" %}
                                <div><small><i class="fas fa-venus"></i> Female</small></div>
                            {% elseif  user.gender  == "2" %}
                                <div><small><i class="fas fa-genderless"></i> Other</small></div>
                            {% endif %}
                        {% endif %}
                        {% if user.birthDate is not empty %}
                            <div><small><i class="fas fa-birthday-cake"></i> {{ user.birthDate|date("F j, Y") }}</small></div>
                        {% endif %}
                        {#<div><p>Photos and videos</p>
                            <ul class="photo-video"></ul>
                        </div>#}
                    </div>
                {% endblock %}
            </div>
            <div class="col-lg-6">
                {% block profile_center %}
                {% endblock %}
            </div>
            <div class="col-lg-3">
                {% block profile_right %}
                    {{ render(controller('App\\Controller\\CommonController::trends')) }}
                {% endblock %}
            </div>
        </div>
    </div>

    {% if app.user is not empty and app.user.id == user.id %}
        {% if (formAvatar ?? null) is not empty %}
            {{ form_start(formAvatar, {'action': path('uploadAvatar'), 'method': 'POST',
                attr: {'class': 'd-none formAvatar'}}) }}
            {{ form_end(formAvatar) }}
        {% endif %}
        {% if (formBanner ?? null) is not empty %}
            {{ form_start(formBanner, {'action': path('uploadBanner'), 'method': 'POST',
                attr: {'class': 'd-none formBanner'}}) }}
            {{ form_end(formBanner) }}
        {% endif %}
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script rel="script" src="{{ asset('assets/js/follow.js') }}"></script>
    <script rel="script" src="{{ asset('assets/js/uploadProfile.js') }}"></script>
{% endblock %}

templates/profile/edit.html.twig
{% extends 'layout-3.html.twig' %}
{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/profile.css') }}">
{% endblock %}
{% form_theme formEdit 'bootstrap_4_layout.html.twig' %}
{% block center_body %}
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Edit Profile</h2>
        </div>
        <div class="card-body">
            {{ form(formEdit) }}
            <button class="reset_color btn btn-primary">Reset Color</button>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('assets/js/colorReset.js') }}"></script>
{% endblock %}

templates/profile/favorites.html.twig
{% extends 'profile/_layout.html.twig' %}

{% block title %}Quacks liked by {{ user.displayName }} (@{{ user.username }}) | Ducker{% endblock %}

{% block profile_center %}
    {% if user.favorites is not empty %}
        <div class="card">
            <div class="card-header">
                <strong>Likes</strong>
            </div>
            <div class="list-group list-group-flush">
                {% for favorite in user.favorites %}
                    {% include 'common/post_card.html.twig' with { post: favorite.post } only %}
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="p-2">
            <p><strong>@{{ user.username }}</strong> has not liked any Quack !</p>
        </div>
    {% endif %}
{% endblock %}

templates/profile/followers.html.twig
{% extends 'profile/_layout.html.twig' %}

{% block title %}People following {{ user.displayName }} (@{{ user.username }}) | Ducker{% endblock %}

{% block profile_center %}
    {% if user.followers is not empty %}

        <div class="card">
            <div class="card-header">
                <strong>Followers</strong>
            </div>
            <div class="list-group list-group-flush">
                <div class="container-fluid">
                    <div class="row">
                        {% for follower in user.followers %}
                            <div class="card col-4">
                                <div class="card-body picture-follow">
                                    <a href="{{ path('profile_view', { username: follower.follower.username }) }}">
                                        {% if follower.follower is not empty and follower.follower.avatarPath is not empty %}
                                            {% set avatarUrl = asset('upload/avatar/'~ follower.follower.avatarPath) %}
                                        {% else %}
                                            {% set avatarUrl = asset('assets/img/user-placeholder.png') %}
                                        {% endif %}
                                        <img alt="Profile picture of {{ follower.follower.username }}" src="{{ avatarUrl }}" class="mini-avatar-64" height="64" width="64">
                                    </a>
                                    <p class="card-body name-follow">
                                    <h6>{{ follower.follower.displayName }}<br></h6>
                                    <h6 class="card-subtitle mb-2 text-muted"> @{{ follower.follower.username }}</h6>
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="p-2">
            <p><strong>@{{ user.username }}</strong> has no followers</p>
        </div>
    {% endif %}
{% endblock %}

templates/profile/following.html.twig
{% extends 'profile/_layout.html.twig' %}

{% block title %}People followed by {{ user.displayName }} (@{{ user.username }}) | Ducker{% endblock %}

{% block profile_center %}
    {% if user.following is not empty %}
        <div class="card">
            <div class="card-header">
                <strong>Following</strong>
            </div>
            <div class="list-group list-group-flush">
                <div class="container-fluid">
                    <div class="row">
                        {% for following in user.following %}
                            <div class="card col-4">
                                <div class="card-body picture-follow">
                                    <a href="{{ path('profile_view', { username: following.user.username }) }}">
                                        {% if following.user is not empty and following.user.avatarPath is not empty %}
                                            {% set avatarUrl = asset('upload/avatar/'~ following.user.avatarPath) %}
                                        {% else %}
                                            {% set avatarUrl = asset('assets/img/user-placeholder.png') %}
                                        {% endif %}
                                        <img alt="Profile picture of @{{ following.user.username }}" src="{{ avatarUrl }}" class="mini-avatar-64">
                                    </a>
                                    <p class="card-body name-follow"></p>
                                    <h6>{{ following.user.displayName }}<br></h6>
                                    <h6 class="card-subtitle mb-2 text-muted">@{{ following.user.username }}</h6>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="p-2">
            <p><strong>@{{ user.username }}</strong> is not following anyone</p>
        </div>
    {% endif %}
{% endblock %}

templates/profile/index.html.twig
{% extends 'profile/_layout.html.twig' %}

{% block title %}{{ user.displayName }} (@{{ user.username }}) | Ducker{% endblock %}

{% block profile_center %}
    {% if user.posts is not empty %}
        <div class="mb-2">
            <nav class="nav nav-pills">
                {% set route = app.request.get('_route') %}
                <a href="{{ path('profile_view', { username: user.username }) }}" class="nav-link {{ route == 'profile_view' ? 'active' }}">Quacks</a>
                <a href="{{ path('profile_view_replies', { username: user.username }) }}" class="nav-link {{ route == 'profile_view_replies' ? 'active' }}">Quacks & Replies</a>
                <a href="{{ path('profile_view_media', { username: user.username }) }}" class="nav-link {{ route == 'profile_view_media' ? 'active' }}">Media</a>
            </nav>
        </div>
        <div class="card">
            <div class="list-group list-group-flush timeline">
                {% for post in posts %}
                    {% include 'common/post_card.html.twig' with { post: post } only %}
                {% endfor %}
            </div>
        </div>
    {% else %}
        {% if app.user is not empty and user.id == app.user.id %}
            <p><strong>Send your first Quack</strong></p>
            <div class="mb-4">
                <div class="card card-body post-maker-container">
                    {{ render(controller('App\\Controller\\CommonController::postMaker')) }}
                </div>
            </div>
        {% else %}
            <div class="p-2">
                <p><strong>@{{ user.username }}</strong> hasn't Quacked</p>
                <p>When they do, their Quacks will show up here.</p>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if USE_EMOJIONE_EDITOR %}
        <script src="{{ asset('assets/js/post_maker_bonus.js') }}"></script>
    {% else %}
        <script src="{{ asset('assets/js/post_maker.js') }}"></script>
    {% endif %}
{% endblock %}