src/Entity/Notification.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotificationRepository")
 */
class Notification
{
    public const TYPE_MENTION = 1;
    public const TYPE_FOLLOW = 2;
    public const TYPE_REPOST = 3;
    public const TYPE_LIKE = 4;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="notifications")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="smallint")
     */
    private $notification_type;

    /**
     * @ORM\Column(type="json")
     */
    private $notification_data = [];

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNotificationType(): ?int
    {
        return $this->notification_type;
    }

    public function setNotificationType(int $notification_type): self
    {
        $this->notification_type = $notification_type;

        return $this;
    }

    public function getNotificationData(): ?array
    {
        return $this->notification_data;
    }

    public function setNotificationData(array $notification_data): self
    {
        $this->notification_data = $notification_data;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=24)
     */
    private $display_name;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="sender")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="user")
     */
    private $notifications;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Follower", mappedBy="user")
     */
    private $followers;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Follower", mappedBy="follower")
     */
    private $following;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ChatConversation", mappedBy="participants")
     */
    private $chatConversations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="user")
     */
    private $favorites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Upload", mappedBy="uploader")
     */
    private $uploads;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $theme_color;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->followers = new ArrayCollection();
        $this->chatConversations = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->uploads = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setSender($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getSender() === $this) {
                $post->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setUser($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getUser() === $this) {
                $notification->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Follower[]
     */
    public function getFollowers(): Collection
    {
        return $this->followers;
    }

    public function addFollower(Follower $follower): self
    {
        if (!$this->followers->contains($follower)) {
            $this->followers[] = $follower;
            $follower->setUser($this);
        }

        return $this;
    }

    public function removeFollower(Follower $follower): self
    {
        if ($this->followers->contains($follower)) {
            $this->followers->removeElement($follower);
            // set the owning side to null (unless already changed)
            if ($follower->getUser() === $this) {
                $follower->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Follower[]
     */
    public function getFollowing(): Collection
    {
        return $this->following;
    }

    /**
     * @return Collection|ChatConversation[]
     */
    public function getChatConversations(): Collection
    {
        return $this->chatConversations;
    }

    public function addChatConversation(ChatConversation $chatConversation): self
    {
        if (!$this->chatConversations->contains($chatConversation)) {
            $this->chatConversations[] = $chatConversation;
            $chatConversation->addParticipant($this);
        }

        return $this;
    }

    public function removeChatConversation(ChatConversation $chatConversation): self
    {
        if ($this->chatConversations->contains($chatConversation)) {
            $this->chatConversations->removeElement($chatConversation);
            $chatConversation->removeParticipant($this);
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setUser($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getUser() === $this) {
                $favorite->setUser(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return 'vive le projet tweet_academy';
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Upload[]
     */
    public function getUploads(): Collection
    {
        return $this->uploads;
    }

    public function addUpload(Upload $upload): self
    {
        if (!$this->uploads->contains($upload)) {
            $this->uploads[] = $upload;
            $upload->setUploader($this);
        }

        return $this;
    }

    public function removeUpload(Upload $upload): self
    {
        if ($this->uploads->contains($upload)) {
            $this->uploads->removeElement($upload);
            // set the owning side to null (unless already changed)
            if ($upload->getUploader() === $this) {
                $upload->setUploader(null);
            }
        }

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(?int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

src/Controller/NotificationsController.php
<?php

namespace App\Controller;

use App\Entity\Notification;
use App\Repository\NotificationRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class NotificationsController extends AbstractController
{
    /**
     * @Route("/notifications", name="notifications")
     * @IsGranted("ROLE_USER", statusCode=403)
     */
    public function index(NotificationRepository $repository, ObjectManager $manager)
    {
        $notifications = $repository->findBy([
            'user' => $this->getUser(),
            'is_read' => false
        ]);

        foreach($notifications as $n)
        {
            $n->setIsRead(true);
            $manager->persist($n);
        }

        $manager->flush();

        return $this->render('notifications/index.html.twig', [
            'notifications' => $notifications
        ]);
    }

    /**
     * @Route("/mentions", name="mentions")
     * @IsGranted("ROLE_USER", statusCode=403)
     */
    public function mentions(NotificationRepository $repository, ObjectManager $manager)
    {
        $notifications = $repository->findBy([
            'user' => $this->getUser(),
            'notification_type' => Notification::TYPE_MENTION,
            'is_read' => false
        ]);

        foreach($notifications as $n)
        {
            $n->setIsRead(true);
            $manager->persist($n);
        }

        $manager->flush();

        return $this->render('notifications/mentions.html.twig', [
            'notifications' => $notifications
        ]);
    }
}

templates/notifications/_card_data.html.twig
<div class="list-group-item">
    {% set EntityType = 'App\\Entity\\Notification' %}
    {% set json = notification.notificationData %}
    {% if notification.notificationType == constant(EntityType ~ '::TYPE_MENTION')
        and user is not empty and post is not empty %}
        <p>User <strong>@{{ user.username }}</strong> mentioned you in a Quack</p>
        <div class="card card-body">
            <div>
                <strong>{{ post.sender.displayName }}</strong>
                <span>(@{{ post.sender.username }}</span>
            </div>
            <p>{{ post.content|format_post|raw }}</p>
        </div>
    {% elseif notification.notificationType == constant(EntityType ~ '::TYPE_FOLLOW')
        and user is not empty %}
        <p>User <a href="{{ path('profile_view', { username: user.username }) }}"><strong>@{{ user.username }}</strong></a> started to follow you</p>
    {% elseif notification.notificationType == constant(EntityType ~ '::TYPE_LIKE')
        and user is not empty and post is not empty %}
        <p>User <strong>@{{ user.username }}</strong> liked your Quack</p>
        <div class="card card-body">
            <div>
                <strong>{{ post.sender.displayName }}</strong>
                <span>(@{{ post.sender.username }})</span>
            </div>
            <p>{{ post.content|format_post|raw }}</p>
        </div>
    {% elseif notification.notificationType == constant(EntityType ~ '::TYPE_REPOST')
        and user is not empty and post is not empty %}
        <p>One of your Quack has been reposted by <strong>@{{ user.username }}</strong></p>
        <div class="card card-body">
            <div>
                <strong>{{ post.sender.displayName }}</strong>
                <span>(@{{ post.sender.username }}</span>
            </div>
            <p>{{ post.content|format_post|raw }}</p>
        </div>
    {% else %}
        <p class="alert alert-danger">Unknown notification type</p>
    {% endif %}
</div>

templates/notifications/_layout.html.twig
{% extends 'layout-3.html.twig' %}

{% block left_sidebar %}
    {{ render(controller('App\\Controller\\CommonController::trends')) }}
{% endblock %}

{% block center_body %}
    <div class="card">
        <div class="card-header">
            <nav class="nav nav-pills">
                {% set route = app.request.get('_route') %}
                <a class="nav-link {{ route == 'notifications' ? 'active' }}" href="{{ path('notifications') }}">All</a>
                <a class="nav-link {{ route == 'mentions' ? 'active' }}" href="{{ path('mentions') }}">Mentions</a>
            </nav>
        </div>
        {% block notifications_body %}
        {% endblock %}
    </div>
{% endblock %}

{% block right_sidebar %}
    {{ render(controller('App\\Controller\\CommonController::footer')) }}
{% endblock %}

templates/notifications/index.html.twig
{% extends 'notifications/_layout.html.twig' %}

{% block title %}Ducker / Notifications{% endblock %}

{% block notifications_body %}
    {% if notifications is empty %}
        <div class="card-body">
            <p>Nothing to see here — yet</p>
        </div>
    {% else %}
        <div class="list-group list-group-flush">
            {% for notification in notifications %}
                {{ render(controller('App\\Controller\\CommonController::notificationCard', {
                    n: notification
                })) }}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/notifications/mentions.html.twig
{% extends 'notifications/_layout.html.twig' %}

{% block title %}Ducker / Mentions{% endblock %}

{% block notifications_body %}
    {% if notifications is empty %}
        <div class="card-body">
            <p>Nothing to see here — yet</p>
            <p>When someone mentions you in a Quack, you'll see it here</p>
        </div>
    {% else %}
        <div class="list-group list-group-flush">
            {% for n in notifications %}
                {% include 'notifications/_card_data.html.twig' with { notification: n } only %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}