src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Post", inversedBy="replies")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $parent_post;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Post", inversedBy="reposts")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $source_post;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $media_url;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $media_type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $submit_time;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="post")
     */
    private $favorites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="parent_post")
     */
    private $replies;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="source_post")
     */
    private $reposts;

    public function __construct()
    {
        $this->favorites = new ArrayCollection();
        $this->replies = new ArrayCollection();
        $this->reposts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getParentPost(): ?self
    {
        return $this->parent_post;
    }

    public function setParentPost(?self $parent_post): self
    {
        $this->parent_post = $parent_post;

        return $this;
    }

    public function getSourcePost(): ?self
    {
        return $this->source_post;
    }

    public function setSourcePost(?self $source_post): self
    {
        $this->source_post = $source_post;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getMediaUrl(): ?string
    {
        return $this->media_url;
    }

    public function setMediaUrl(?string $media_url): self
    {
        $this->media_url = $media_url;

        return $this;
    }

    public function getMediaType(): ?int
    {
        return $this->media_type;
    }

    public function setMediaType(?int $media_type): self
    {
        $this->media_type = $media_type;

        return $this;
    }

    public function getSubmitTime(): ?\DateTimeInterface
    {
        return $this->submit_time;
    }

    public function setSubmitTime(\DateTimeInterface $submit_time): self
    {
        $this->submit_time = $submit_time;

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setPost($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getPost() === $this) {
                $favorite->setPost(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection|Post[]
     */
    public function getReplies(): Collection
    {
        return $this->replies;
    }

    public function addReply(Post $post): self
    {
        if (!$this->replies->contains($post)) {
            $this->replies[] = $post;
            $post->setParentPost($this);
        }

        return $this;
    }

    public function removeReply(Post $post): self
    {
        if ($this->replies->contains($post)) {
            $this->replies->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getParentPost() === $this) {
                $post->setParentPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getReposts(): Collection
    {
        return $this->reposts;
    }

    public function addRepost(Post $post): self
    {
        if (!$this->reposts->contains($post)) {
            $this->reposts[] = $post;
            $post->setSourcePost($this);
        }

        return $this;
    }

    public function removeRepost(Post $post): self
    {
        if ($this->reposts->contains($post)) {
            $this->reposts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getSourcePost() === $this) {
                $post->setSourcePost(null);
            }
        }

        return $this;
    }

    public function isLikedBy(User $user) : bool
    {
        $user_id = $user->getId();

        return $this->getFavorites()->exists(
            function($key, $entry) use ($user_id) {
                /** @var Favorite $entry */
                return $entry->getUser()->getId() == $user_id;
            }
        );
    }

    public function isRepostedBy(User $user) : bool
    {
        $user_id = $user->getId();

        return $this->getReposts()->exists(
            function($key, $entry) use ($user_id) {
                /** @var Post $entry */
                return $entry->getSender()->getId() == $user_id;
            }
        );
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=24)
     */
    private $display_name;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="sender")
     */
    private $posts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="user")
     */
    private $notifications;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Follower", mappedBy="user")
     */
    private $followers;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Follower", mappedBy="follower")
     */
    private $following;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ChatConversation", mappedBy="participants")
     */
    private $chatConversations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Favorite", mappedBy="user")
     */
    private $favorites;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Upload", mappedBy="uploader")
     */
    private $uploads;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $theme_color;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->followers = new ArrayCollection();
        $this->chatConversations = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->uploads = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setSender($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getSender() === $this) {
                $post->setSender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setUser($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            // set the owning side to null (unless already changed)
            if ($notification->getUser() === $this) {
                $notification->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Follower[]
     */
    public function getFollowers(): Collection
    {
        return $this->followers;
    }

    public function addFollower(Follower $follower): self
    {
        if (!$this->followers->contains($follower)) {
            $this->followers[] = $follower;
            $follower->setUser($this);
        }

        return $this;
    }

    public function removeFollower(Follower $follower): self
    {
        if ($this->followers->contains($follower)) {
            $this->followers->removeElement($follower);
            // set the owning side to null (unless already changed)
            if ($follower->getUser() === $this) {
                $follower->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Follower[]
     */
    public function getFollowing(): Collection
    {
        return $this->following;
    }

    /**
     * @return Collection|ChatConversation[]
     */
    public function getChatConversations(): Collection
    {
        return $this->chatConversations;
    }

    public function addChatConversation(ChatConversation $chatConversation): self
    {
        if (!$this->chatConversations->contains($chatConversation)) {
            $this->chatConversations[] = $chatConversation;
            $chatConversation->addParticipant($this);
        }

        return $this;
    }

    public function removeChatConversation(ChatConversation $chatConversation): self
    {
        if ($this->chatConversations->contains($chatConversation)) {
            $this->chatConversations->removeElement($chatConversation);
            $chatConversation->removeParticipant($this);
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->setUser($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            // set the owning side to null (unless already changed)
            if ($favorite->getUser() === $this) {
                $favorite->setUser(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return 'vive le projet tweet_academy';
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Upload[]
     */
    public function getUploads(): Collection
    {
        return $this->uploads;
    }

    public function addUpload(Upload $upload): self
    {
        if (!$this->uploads->contains($upload)) {
            $this->uploads[] = $upload;
            $upload->setUploader($this);
        }

        return $this;
    }

    public function removeUpload(Upload $upload): self
    {
        if ($this->uploads->contains($upload)) {
            $this->uploads->removeElement($upload);
            // set the owning side to null (unless already changed)
            if ($upload->getUploader() === $this) {
                $upload->setUploader(null);
            }
        }

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(?int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

templates/common/mini_profile.html.twig
<div class="card card-body mini-user-profile">
    {% if app.user is not empty %}
        <div>
            <a href="{{ path('profile_view', { username: app.user.username }) }}">
                <strong>{{ app.user.displayName }}</strong>
                <p>@{{ app.user.username }}</p>
            </a>
        </div>
        <div class="d-flex flex-row">
            <div>
                <div><small>Quacks</small></div>
                <div><strong class="mini-profile__meta-number">{{ (app.user.posts|length)|number_format }}</strong></div>
            </div>
            <div class="mx-2">
                <div><small>Following</small></div>
                <div><strong class="mini-profile__meta-number">{{ (app.user.following|length)|number_format }}</strong></div>
            </div>
            <div class="mx-2">
                <div><small>Followers</small></div>
                <div><strong class="mini-profile__meta-number">{{ (app.user.followers|length)|number_format }}</strong></div>
            </div>
        </div>
    {% else %}
        <button class="btn btn-primary">Log in</button>
    {% endif %}
</div>

templates/common/mini_user_card.html.twig
<div class="card card-body mini_user_card">
    <div class="d-flex justify-content-around">
        <div>
            {% if user.avatarPath == null %}
                <img src="{{ asset('assets/img/user-placeholder.png') }}">
            {% else %}
                <img src="{{ asset('upload/avatar/' ~ user.avatarPath) }}">
            {% endif %}
        </div>
        <div class="d-flex flex-column">
            <span class="username">@{{ user.username }}</span>
            <span>{{ user.displayName }}</span>
        </div>
    </div>
</div>

templates/common/notafooter.html.twig
<div class="p-1">
    <p>&copy; 2019 Ducker</p>
</div>

templates/common/post_card.html.twig
<div class="list-group-item list-group-item-action card-timeline post-card" data-post-id="{{ post.id }}" itemscope itemtype="http://schema.org/SocialMediaPosting">
    <div>
        {# == Displays when the post has been reposted #}
        {% if post.sourcePost is not empty %}
            <div class="post-card__repost-info">
                <i class="fas fa-retweet"></i>
                <span><a href="{{ path('profile_view', { username: post.sender.username }) }}">{{ post.sender.displayName }}</a> Copyquacked</span>
            </div>
        {% elseif post.parentPost is not empty %}
            <div class="post-card__repost-info">
                <i class="fas fa-reply"></i>
                <span>Replying to <a href="{{ path('profile_view', { username: post.parentPost.sender.username }) }}">@{{ post.parentPost.sender.username }}</a></span>
            </div>
        {% endif %}

        {# This helps prevent duplicating code #}
        {% set realPost = post.sourcePost ?? post %}

        {# == Displays the post content #}
        <div class="my-2 d-flex flex-row" itemprop="author" itemscope itemtype="http://schema.org/Person">
            {% if realPost.sender is not empty and realPost.sender.avatarPath is not empty %}
                {% set avatarUrl = asset('upload/avatar/'~ realPost.sender.avatarPath) %}
            {% else %}
                {% set avatarUrl = asset('assets/img/user-placeholder.png') %}
            {% endif %}
            <div>
                <img src="{{ avatarUrl }}" class="mini-avatar-48" height="48px" width="48px">
            </div>
            <div class="post-card__author_content pl-2">
                <a class="post-card__author-name" href="{{ path('profile_view', { username: realPost.sender.username }) }}">
                    <strong itemprop="name">{{ realPost.sender.displayName }}</strong>
                </a>
                <span class="post-card__username">(@{{ realPost.sender.username }})</span>
                <p itemprop="text">{{ realPost.content|format_post|raw }}</p>
            </div>
        </div>

        {# Displays embedded content if any #}
        {# TODO: Add video/audio support #}

        {% if realPost.mediaUrl is not empty %}
            <img itemprop="image" class="img-fluid rounded mx-auto d-block" src="{{ path('media_bin', { id: realPost.id }) }}">
        {% endif %}
    </div>
    <div class="pt-2">
        {% if app.user is not empty %}
            {% set likedByUser = realPost.isLikedBy(app.user) %}
            {% set repostedByUser = realPost.isRepostedBy(app.user) %}
        {% else %}
            {% set likedByUser = false %}
            {% set repostedByUser = false %}
        {% endif %}

        {% set repostBtnClass = repostedByUser ? 'btn-outline-success' : 'btn-outline-secondary' %}
        {% set likeBtnClass = likedByUser ? 'btn-outline-danger' : 'btn-outline-secondary' %}

        <a href="{{ path('view_post', {id: realPost.id}) }}" class="btn btn-outline-secondary btn-sm" title="Comment">
            <i class="far fa-comment"></i>
            <span>{{ realPost.replies|length }}</span>
        </a>
        <button class="btn {{ repostBtnClass }} btn-sm post-card__repost-btn" title="Copyquack">
            <i class="fas fa-retweet"></i>
            <span class="post-card__repost-count">{{ realPost.reposts|length }}</span>
        </button>
        <button class="btn {{ likeBtnClass }} btn-sm post-card__like-btn" title="Like">
            <i class="far fa-heart"></i>
            <span class="post-card__like-count">{{ realPost.favorites|length }}</span>
        </button>
        {#<button class="btn btn-outline-secondary btn-sm" title="Direct message">
            <i class="far fa-envelope"></i>
        </button>#}
        {% if app.user is not empty and post.sender.id == app.user.id %}
            <button class="btn btn-danger btn-sm post-card__delete-btn" title="Delete"><i class="far fa-trash-alt"></i></button>
        {% endif %}

        <div class="text-right post-card__send-time">
            {{ post.submitTime|time_diff }}
        </div>
    </div>
</div>

templates/common/post_maker.html.twig
{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('assets/css/post_maker.css') }}">
{% endblock %}

{% set defaultPlaceholder = 'What\'s quacking ?' %}
{% set placeholder = inputPlaceholder ?? defaultPlaceholder %}

<div id="post_maker-wrapper" class="post_maker-wrapper">
    <div class="d-flex post_maker">
        <span>
            {% if app.user.avatarPath is empty %}
                <img src="{{ asset('assets/img/user-placeholder.png') }}" height="32" width="32" alt="Profile picture" class="mini-avatar">
            {% else %}
                <img src="{{ asset('upload/avatar/'~ app.user.avatarPath) }}" height="32" width="32" alt="Profile picture" class="mini-avatar">
            {% endif %}
        </span>
        {{ form_start(formPost, {attr: {'id': 'formPostMaker'}}) }}
        {{ form_row(formPost.content, {attr: {'placeholder': placeholder }}) }}
        <div class="d-none">
            {{ form_row(formPost.media_url, {attr: {'class': 'inputUpload'}}) }}
        </div>
        {{ form_row(formPost.parent_post_id, {value: parentPostId ?? null}) }}
        {{ form_end(formPost) }}
    </div>
    <span class="quacker-btn-displayer">
        <span class="d-flex justify-content-between quacker-btn-displayer">
            <span></span>
            <span>
                <button class="btn add-file-post_maker"><img src="{{ asset('assets/img/paper-clip.png') }}"></button>
                <button class="submit-post_maker btn btn-primary">Quacker</button>
            </span>
        </span>
    </span>
</div>
<div class="suggestions"></div>

templates/common/suggestions.html.twig
{% if suggestions is not empty %}
<div class="card">
    <strong class="card-header">Who to follow</strong>
    <div class="card-body">
        <div class="list-group list-group-flush">
            {% for user in suggestions %}
                <div class="list-item">
                    <strong>{{ user.displayName }}</strong>
                    <p class="card-subtitle">@{{ user.username }}</p>
                    <button class="btn btn-primary follow-home" data-user-id="{{ user.username }}">Follow</button>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}

templates/common/tek2_promo.html.twig
<div class="container" style="padding-top: 1.5rem;">
	<div class="alert alert-info" role="alert">
	    <strong>Welcome to Ducker !</strong>
	    <p><img class="tek2-epitech-logo float-right d-none d-md-inline" src="{{ asset('tek2promo/epitech.png') }}">This project has been developed by students of the Epitech Web@cadémie training over a period of 2 weeks, it has been left as-is since then.<br />We used the following technologies : Symfony 4, Bootstrap, EmojiOne.</p>
	    <p>Participating students &dash; click to access their LinkedIn profile :</p>
	    
	    <div class="tek2promo--students d-flex">
	        <div class="tek2student">
	            <a href="https://www.linkedin.com/in/emilie-lepine-914779151/">
	            <div class="tek2student--image"><img class="rounded-circle" src="{{ asset('tek2promo/emilie.jpeg') }}"></div>
	            <span>Emilie Lepine</span>
	            </a>
	        </div>
	        
	        <div class="tek2student">
	        <a href="https://www.linkedin.com/in/mteterel/">
	            <div class="tek2student--image"><img class="rounded-circle" src="{{ asset('tek2promo/merill.jpeg') }}"></div>
	            <span>Mérill Téterel</span>
	            </a>
	        </div>
	        
	        <div class="tek2student">
	            <a href="https://www.linkedin.com/in/louis-michalak-87a15317a">
	            <div class="tek2student--image"><img class="rounded-circle" src="{{ asset('tek2promo/louis.jpeg') }}"></div>
	            <span>Louis Michalak</span></a>
	        </div>
	        
	        <div class="tek2student">
  	            <a href="https://www.linkedin.com/in/louison-druelle-905600190/">
	            <div class="tek2student--image"><img class="rounded-circle" src="{{ asset('tek2promo/louison.jpeg') }}"></div>
                <span>Louison Druelle</span>
                </a>
	        </div>
	    </div>
	</div>
</div>

<style>
    .tek2student img {
        text-align: center;
        max-width: 96px;
        height: auto;
     }
     
     .tek2promo--students {
        align-items: middle;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
     }
     
     .tek2student {
        text-align: center;
        padding-left: 1rem;
        padding-right: 1rem;
     }
     
     .tek2-epitech-logo {
        width: 150px;
        height: auto;
     }
</style>

templates/common/trends.html.twig
{% if trends is not empty %}
<div class="card trends trends-list">
    <div class="card-header">
        <strong>Trends</strong>
    </div>
    <div class="card-body">
        {% for t in trends %}
            <div>
                <a class="trend-list__link" href="{{ path('hashtag_search', { name: t.name|slice(1) }) }}">{{ t.name }}</a>
                <p>{{ t.useCount }} {{ t.useCount == 1 ? 'Quack' : 'Quacks' }}</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endif %}